"""Initial schema — 28 tables across all fraud platform layers

Revision ID: db07135787cf
Revises: 
Create Date: 2026-03-10 14:21:47.861347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'db07135787cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_trace',
    sa.Column('trace_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=100), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index(op.f('ix_agent_trace_auth_event_id'), 'agent_trace', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_agent_trace_case_id'), 'agent_trace', ['case_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_event_entity_id'), 'audit_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_event_entity_type'), 'audit_event', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_event_event_type'), 'audit_event', ['event_type'], unique=False)
    op.create_table('dim_customer',
    sa.Column('customer_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_customer_ref', sa.String(length=255), nullable=True),
    sa.Column('customer_since_dt', sa.Date(), nullable=True),
    sa.Column('kyc_status', sa.String(length=50), nullable=True),
    sa.Column('risk_segment', sa.String(length=20), nullable=True),
    sa.Column('home_country_code', sa.String(length=2), nullable=True),
    sa.Column('home_region', sa.String(length=100), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_dim_customer_external_customer_ref'), 'dim_customer', ['external_customer_ref'], unique=True)
    op.create_table('dim_device',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=512), nullable=True),
    sa.Column('os_family', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('browser_family', sa.String(length=100), nullable=True),
    sa.Column('emulator_flag', sa.Boolean(), nullable=True),
    sa.Column('rooted_jailbroken_flag', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_dim_device_device_fingerprint'), 'dim_device', ['device_fingerprint'], unique=False)
    op.create_table('dim_ip',
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('geo_country_code', sa.String(length=2), nullable=True),
    sa.Column('geo_region', sa.String(length=200), nullable=True),
    sa.Column('geo_city', sa.String(length=200), nullable=True),
    sa.Column('asn', sa.String(length=100), nullable=True),
    sa.Column('proxy_vpn_tor_flag', sa.Boolean(), nullable=True),
    sa.Column('hosting_provider_flag', sa.Boolean(), nullable=True),
    sa.Column('ip_risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.create_table('dim_merchant',
    sa.Column('merchant_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('merchant_name', sa.String(length=500), nullable=True),
    sa.Column('mcc', sa.String(length=10), nullable=True),
    sa.Column('merchant_category', sa.String(length=200), nullable=True),
    sa.Column('acquirer_id', sa.String(length=100), nullable=True),
    sa.Column('merchant_country_code', sa.String(length=2), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('onboarding_date', sa.Date(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_index(op.f('ix_dim_merchant_mcc'), 'dim_merchant', ['mcc'], unique=False)
    op.create_table('dim_model_registry',
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('model_family', sa.String(length=100), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('training_data_start', sa.Date(), nullable=True),
    sa.Column('training_data_end', sa.Date(), nullable=True),
    sa.Column('feature_version', sa.String(length=50), nullable=True),
    sa.Column('threshold_decline', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('threshold_review', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('threshold_stepup', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('deployment_status', sa.String(length=30), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('model_version')
    )
    op.create_table('fact_chargeback_case',
    sa.Column('chargeback_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=True),
    sa.Column('chargeback_reason_code', sa.String(length=50), nullable=True),
    sa.Column('chargeback_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('chargeback_received_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('representment_flag', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('outcome_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('chargeback_id')
    )
    op.create_index(op.f('ix_fact_chargeback_case_auth_event_id'), 'fact_chargeback_case', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_chargeback_case_transaction_id'), 'fact_chargeback_case', ['transaction_id'], unique=False)
    op.create_table('fact_feature_drift_metric',
    sa.Column('drift_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('feature_name', sa.String(length=200), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('psi', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('js_divergence', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('null_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('train_mean', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('prod_mean', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('alert_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('drift_id')
    )
    op.create_index(op.f('ix_fact_feature_drift_metric_metric_date'), 'fact_feature_drift_metric', ['metric_date'], unique=False)
    op.create_index(op.f('ix_fact_feature_drift_metric_model_version'), 'fact_feature_drift_metric', ['model_version'], unique=False)
    op.create_table('fact_graph_cluster_score',
    sa.Column('cluster_score_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_id', sa.String(length=255), nullable=True),
    sa.Column('cluster_size', sa.Integer(), nullable=True),
    sa.Column('risky_neighbor_count', sa.Integer(), nullable=True),
    sa.Column('hop2_risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('synthetic_identity_flag', sa.Boolean(), nullable=True),
    sa.Column('mule_pattern_flag', sa.Boolean(), nullable=True),
    sa.Column('score_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cluster_score_id')
    )
    op.create_index(op.f('ix_fact_graph_cluster_score_auth_event_id'), 'fact_graph_cluster_score', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_graph_cluster_score_cluster_id'), 'fact_graph_cluster_score', ['cluster_id'], unique=False)
    op.create_table('fact_label_snapshot',
    sa.Column('snapshot_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('label_status', sa.String(length=50), nullable=True),
    sa.Column('is_fraud_snapshot', sa.Boolean(), nullable=True),
    sa.Column('maturity_days', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_fact_label_snapshot_auth_event_id'), 'fact_label_snapshot', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_label_snapshot_snapshot_date'), 'fact_label_snapshot', ['snapshot_date'], unique=False)
    op.create_table('fact_model_eval_metric',
    sa.Column('eval_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('eval_date', sa.Date(), nullable=False),
    sa.Column('segment_name', sa.String(length=100), nullable=True),
    sa.Column('population_name', sa.String(length=100), nullable=True),
    sa.Column('auc_roc', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('auc_pr', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('precision_at_decline', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('recall_at_decline', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('false_positive_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('false_negative_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('approval_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('decline_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('review_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('expected_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('prevented_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('eval_window_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('eval_window_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('eval_id')
    )
    op.create_index(op.f('ix_fact_model_eval_metric_eval_date'), 'fact_model_eval_metric', ['eval_date'], unique=False)
    op.create_index(op.f('ix_fact_model_eval_metric_model_version'), 'fact_model_eval_metric', ['model_version'], unique=False)
    op.create_table('fact_threshold_experiment',
    sa.Column('experiment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('challenger_model_version', sa.String(length=100), nullable=False),
    sa.Column('champion_model_version', sa.String(length=100), nullable=False),
    sa.Column('threshold_set_version', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('traffic_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('outcome_summary_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_table('fact_transaction_features_offline',
    sa.Column('offline_feature_row_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('label_snapshot_date', sa.Date(), nullable=True),
    sa.Column('feature_json', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('offline_feature_row_id')
    )
    op.create_index(op.f('ix_fact_transaction_features_offline_auth_event_id'), 'fact_transaction_features_offline', ['auth_event_id'], unique=False)
    op.create_table('fact_transaction_lifecycle_event',
    sa.Column('lifecycle_event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('lifecycle_event_id')
    )
    op.create_index(op.f('ix_fact_transaction_lifecycle_event_auth_event_id'), 'fact_transaction_lifecycle_event', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_transaction_lifecycle_event_event_type'), 'fact_transaction_lifecycle_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_fact_transaction_lifecycle_event_transaction_id'), 'fact_transaction_lifecycle_event', ['transaction_id'], unique=False)
    op.create_table('graph_entity_edge',
    sa.Column('edge_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('src_node_id', sa.String(length=255), nullable=False),
    sa.Column('dst_node_id', sa.String(length=255), nullable=False),
    sa.Column('edge_type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('attributes_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index(op.f('ix_graph_entity_edge_dst_node_id'), 'graph_entity_edge', ['dst_node_id'], unique=False)
    op.create_index(op.f('ix_graph_entity_edge_edge_type'), 'graph_entity_edge', ['edge_type'], unique=False)
    op.create_index(op.f('ix_graph_entity_edge_src_node_id'), 'graph_entity_edge', ['src_node_id'], unique=False)
    op.create_table('graph_entity_node',
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('entity_ref', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('attributes_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index(op.f('ix_graph_entity_node_entity_ref'), 'graph_entity_node', ['entity_ref'], unique=False)
    op.create_index(op.f('ix_graph_entity_node_node_type'), 'graph_entity_node', ['node_type'], unique=False)
    op.create_table('dim_account',
    sa.Column('account_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('account_status', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('billing_country_code', sa.String(length=2), nullable=True),
    sa.Column('autopay_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_dim_account_customer_id'), 'dim_account', ['customer_id'], unique=False)
    op.create_table('dim_card',
    sa.Column('card_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('pan_token', sa.String(length=255), nullable=True),
    sa.Column('card_product', sa.String(length=100), nullable=True),
    sa.Column('network', sa.String(length=50), nullable=True),
    sa.Column('card_status', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_month', sa.Integer(), nullable=True),
    sa.Column('expiry_year', sa.Integer(), nullable=True),
    sa.Column('wallet_tokenized_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['dim_account.account_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_dim_card_account_id'), 'dim_card', ['account_id'], unique=False)
    op.create_index(op.f('ix_dim_card_pan_token'), 'dim_card', ['pan_token'], unique=True)
    op.create_table('fact_authorization_event',
    sa.Column('auth_event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('card_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('merchant_id', sa.BigInteger(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('entry_mode', sa.String(length=30), nullable=True),
    sa.Column('auth_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('merchant_country_code', sa.String(length=2), nullable=True),
    sa.Column('billing_amount_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('velocity_bucket', sa.String(length=50), nullable=True),
    sa.Column('auth_status', sa.String(length=30), nullable=True),
    sa.Column('decline_reason_code', sa.String(length=50), nullable=True),
    sa.Column('challenge_type', sa.String(length=50), nullable=True),
    sa.Column('request_payload_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['dim_account.account_id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['dim_card.card_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['dim_device.device_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['dim_merchant.merchant_id'], ),
    sa.PrimaryKeyConstraint('auth_event_id')
    )
    op.create_index(op.f('ix_fact_authorization_event_account_id'), 'fact_authorization_event', ['account_id'], unique=False)
    op.create_index(op.f('ix_fact_authorization_event_auth_status'), 'fact_authorization_event', ['auth_status'], unique=False)
    op.create_index(op.f('ix_fact_authorization_event_card_id'), 'fact_authorization_event', ['card_id'], unique=False)
    op.create_index(op.f('ix_fact_authorization_event_customer_id'), 'fact_authorization_event', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fact_authorization_event_event_time'), 'fact_authorization_event', ['event_time'], unique=False)
    op.create_index(op.f('ix_fact_authorization_event_merchant_id'), 'fact_authorization_event', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_fact_authorization_event_transaction_id'), 'fact_authorization_event', ['transaction_id'], unique=False)
    op.create_table('fact_clearing_event',
    sa.Column('clearing_event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=True),
    sa.Column('clearing_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('clearing_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('settlement_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['auth_event_id'], ['fact_authorization_event.auth_event_id'], ),
    sa.PrimaryKeyConstraint('clearing_event_id')
    )
    op.create_index(op.f('ix_fact_clearing_event_auth_event_id'), 'fact_clearing_event', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_clearing_event_transaction_id'), 'fact_clearing_event', ['transaction_id'], unique=False)
    op.create_table('fact_decision',
    sa.Column('decision_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=False),
    sa.Column('decision_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('final_risk_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('decision_source', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('rule_set_version', sa.String(length=100), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('manual_override_flag', sa.Boolean(), nullable=True),
    sa.Column('manual_override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['auth_event_id'], ['fact_authorization_event.auth_event_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_fact_decision_auth_event_id'), 'fact_decision', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_decision_decision_type'), 'fact_decision', ['decision_type'], unique=False)
    op.create_table('fact_fraud_case',
    sa.Column('case_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=False),
    sa.Column('case_status', sa.String(length=50), nullable=True),
    sa.Column('queue_name', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auth_event_id'], ['fact_authorization_event.auth_event_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_fact_fraud_case_auth_event_id'), 'fact_fraud_case', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_fraud_case_case_status'), 'fact_fraud_case', ['case_status'], unique=False)
    op.create_index(op.f('ix_fact_fraud_case_queue_name'), 'fact_fraud_case', ['queue_name'], unique=False)
    op.create_table('fact_fraud_label',
    sa.Column('label_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('label_type', sa.String(length=50), nullable=False),
    sa.Column('is_fraud', sa.Boolean(), nullable=False),
    sa.Column('fraud_category', sa.String(length=100), nullable=True),
    sa.Column('fraud_subcategory', sa.String(length=100), nullable=True),
    sa.Column('label_source', sa.String(length=100), nullable=False),
    sa.Column('source_confidence', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('event_occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('label_received_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('effective_label_date', sa.Date(), nullable=False),
    sa.Column('investigator_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['auth_event_id'], ['fact_authorization_event.auth_event_id'], ),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_index(op.f('ix_fact_fraud_label_auth_event_id'), 'fact_fraud_label', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_fraud_label_effective_label_date'), 'fact_fraud_label', ['effective_label_date'], unique=False)
    op.create_index(op.f('ix_fact_fraud_label_transaction_id'), 'fact_fraud_label', ['transaction_id'], unique=False)
    op.create_table('fact_model_score',
    sa.Column('score_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('score_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fraud_probability', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('calibrated_probability', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('predicted_label', sa.Boolean(), nullable=True),
    sa.Column('risk_band', sa.String(length=20), nullable=True),
    sa.Column('top_reason_codes', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('shap_values_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('shadow_mode_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['auth_event_id'], ['fact_authorization_event.auth_event_id'], ),
    sa.ForeignKeyConstraint(['model_version'], ['dim_model_registry.model_version'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index(op.f('ix_fact_model_score_auth_event_id'), 'fact_model_score', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_model_score_model_version'), 'fact_model_score', ['model_version'], unique=False)
    op.create_table('fact_rule_score',
    sa.Column('rule_score_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_set_version', sa.String(length=100), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('rule_name', sa.String(length=300), nullable=True),
    sa.Column('fired_flag', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('contribution_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('score_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_event_id'], ['fact_authorization_event.auth_event_id'], ),
    sa.PrimaryKeyConstraint('rule_score_id')
    )
    op.create_index(op.f('ix_fact_rule_score_auth_event_id'), 'fact_rule_score', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_fact_rule_score_rule_id'), 'fact_rule_score', ['rule_id'], unique=False)
    op.create_table('fact_transaction_features_online',
    sa.Column('feature_row_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=False),
    sa.Column('feature_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('customer_txn_count_1h', sa.Integer(), nullable=True),
    sa.Column('customer_txn_count_24h', sa.Integer(), nullable=True),
    sa.Column('customer_spend_24h', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('card_txn_count_10m', sa.Integer(), nullable=True),
    sa.Column('merchant_txn_count_10m', sa.Integer(), nullable=True),
    sa.Column('merchant_chargeback_rate_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('device_txn_count_1d', sa.Integer(), nullable=True),
    sa.Column('device_account_count_30d', sa.Integer(), nullable=True),
    sa.Column('ip_account_count_7d', sa.Integer(), nullable=True),
    sa.Column('ip_card_count_7d', sa.Integer(), nullable=True),
    sa.Column('geo_distance_from_home_km', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('geo_distance_from_last_txn_km', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('seconds_since_last_txn', sa.BigInteger(), nullable=True),
    sa.Column('amount_vs_customer_p95_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount_vs_merchant_p95_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('proxy_vpn_tor_flag', sa.Boolean(), nullable=True),
    sa.Column('device_risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('behavioral_risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('graph_cluster_risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('feature_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['auth_event_id'], ['fact_authorization_event.auth_event_id'], ),
    sa.PrimaryKeyConstraint('feature_row_id')
    )
    op.create_index(op.f('ix_fact_transaction_features_online_auth_event_id'), 'fact_transaction_features_online', ['auth_event_id'], unique=True)
    op.create_table('fact_case_action',
    sa.Column('case_action_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['fact_fraud_case.case_id'], ),
    sa.PrimaryKeyConstraint('case_action_id')
    )
    op.create_index(op.f('ix_fact_case_action_case_id'), 'fact_case_action', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_case_action_case_id'), table_name='fact_case_action')
    op.drop_table('fact_case_action')
    op.drop_index(op.f('ix_fact_transaction_features_online_auth_event_id'), table_name='fact_transaction_features_online')
    op.drop_table('fact_transaction_features_online')
    op.drop_index(op.f('ix_fact_rule_score_rule_id'), table_name='fact_rule_score')
    op.drop_index(op.f('ix_fact_rule_score_auth_event_id'), table_name='fact_rule_score')
    op.drop_table('fact_rule_score')
    op.drop_index(op.f('ix_fact_model_score_model_version'), table_name='fact_model_score')
    op.drop_index(op.f('ix_fact_model_score_auth_event_id'), table_name='fact_model_score')
    op.drop_table('fact_model_score')
    op.drop_index(op.f('ix_fact_fraud_label_transaction_id'), table_name='fact_fraud_label')
    op.drop_index(op.f('ix_fact_fraud_label_effective_label_date'), table_name='fact_fraud_label')
    op.drop_index(op.f('ix_fact_fraud_label_auth_event_id'), table_name='fact_fraud_label')
    op.drop_table('fact_fraud_label')
    op.drop_index(op.f('ix_fact_fraud_case_queue_name'), table_name='fact_fraud_case')
    op.drop_index(op.f('ix_fact_fraud_case_case_status'), table_name='fact_fraud_case')
    op.drop_index(op.f('ix_fact_fraud_case_auth_event_id'), table_name='fact_fraud_case')
    op.drop_table('fact_fraud_case')
    op.drop_index(op.f('ix_fact_decision_decision_type'), table_name='fact_decision')
    op.drop_index(op.f('ix_fact_decision_auth_event_id'), table_name='fact_decision')
    op.drop_table('fact_decision')
    op.drop_index(op.f('ix_fact_clearing_event_transaction_id'), table_name='fact_clearing_event')
    op.drop_index(op.f('ix_fact_clearing_event_auth_event_id'), table_name='fact_clearing_event')
    op.drop_table('fact_clearing_event')
    op.drop_index(op.f('ix_fact_authorization_event_transaction_id'), table_name='fact_authorization_event')
    op.drop_index(op.f('ix_fact_authorization_event_merchant_id'), table_name='fact_authorization_event')
    op.drop_index(op.f('ix_fact_authorization_event_event_time'), table_name='fact_authorization_event')
    op.drop_index(op.f('ix_fact_authorization_event_customer_id'), table_name='fact_authorization_event')
    op.drop_index(op.f('ix_fact_authorization_event_card_id'), table_name='fact_authorization_event')
    op.drop_index(op.f('ix_fact_authorization_event_auth_status'), table_name='fact_authorization_event')
    op.drop_index(op.f('ix_fact_authorization_event_account_id'), table_name='fact_authorization_event')
    op.drop_table('fact_authorization_event')
    op.drop_index(op.f('ix_dim_card_pan_token'), table_name='dim_card')
    op.drop_index(op.f('ix_dim_card_account_id'), table_name='dim_card')
    op.drop_table('dim_card')
    op.drop_index(op.f('ix_dim_account_customer_id'), table_name='dim_account')
    op.drop_table('dim_account')
    op.drop_index(op.f('ix_graph_entity_node_node_type'), table_name='graph_entity_node')
    op.drop_index(op.f('ix_graph_entity_node_entity_ref'), table_name='graph_entity_node')
    op.drop_table('graph_entity_node')
    op.drop_index(op.f('ix_graph_entity_edge_src_node_id'), table_name='graph_entity_edge')
    op.drop_index(op.f('ix_graph_entity_edge_edge_type'), table_name='graph_entity_edge')
    op.drop_index(op.f('ix_graph_entity_edge_dst_node_id'), table_name='graph_entity_edge')
    op.drop_table('graph_entity_edge')
    op.drop_index(op.f('ix_fact_transaction_lifecycle_event_transaction_id'), table_name='fact_transaction_lifecycle_event')
    op.drop_index(op.f('ix_fact_transaction_lifecycle_event_event_type'), table_name='fact_transaction_lifecycle_event')
    op.drop_index(op.f('ix_fact_transaction_lifecycle_event_auth_event_id'), table_name='fact_transaction_lifecycle_event')
    op.drop_table('fact_transaction_lifecycle_event')
    op.drop_index(op.f('ix_fact_transaction_features_offline_auth_event_id'), table_name='fact_transaction_features_offline')
    op.drop_table('fact_transaction_features_offline')
    op.drop_table('fact_threshold_experiment')
    op.drop_index(op.f('ix_fact_model_eval_metric_model_version'), table_name='fact_model_eval_metric')
    op.drop_index(op.f('ix_fact_model_eval_metric_eval_date'), table_name='fact_model_eval_metric')
    op.drop_table('fact_model_eval_metric')
    op.drop_index(op.f('ix_fact_label_snapshot_snapshot_date'), table_name='fact_label_snapshot')
    op.drop_index(op.f('ix_fact_label_snapshot_auth_event_id'), table_name='fact_label_snapshot')
    op.drop_table('fact_label_snapshot')
    op.drop_index(op.f('ix_fact_graph_cluster_score_cluster_id'), table_name='fact_graph_cluster_score')
    op.drop_index(op.f('ix_fact_graph_cluster_score_auth_event_id'), table_name='fact_graph_cluster_score')
    op.drop_table('fact_graph_cluster_score')
    op.drop_index(op.f('ix_fact_feature_drift_metric_model_version'), table_name='fact_feature_drift_metric')
    op.drop_index(op.f('ix_fact_feature_drift_metric_metric_date'), table_name='fact_feature_drift_metric')
    op.drop_table('fact_feature_drift_metric')
    op.drop_index(op.f('ix_fact_chargeback_case_transaction_id'), table_name='fact_chargeback_case')
    op.drop_index(op.f('ix_fact_chargeback_case_auth_event_id'), table_name='fact_chargeback_case')
    op.drop_table('fact_chargeback_case')
    op.drop_table('dim_model_registry')
    op.drop_index(op.f('ix_dim_merchant_mcc'), table_name='dim_merchant')
    op.drop_table('dim_merchant')
    op.drop_table('dim_ip')
    op.drop_index(op.f('ix_dim_device_device_fingerprint'), table_name='dim_device')
    op.drop_table('dim_device')
    op.drop_index(op.f('ix_dim_customer_external_customer_ref'), table_name='dim_customer')
    op.drop_table('dim_customer')
    op.drop_index(op.f('ix_audit_event_event_type'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity_type'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_agent_trace_case_id'), table_name='agent_trace')
    op.drop_index(op.f('ix_agent_trace_auth_event_id'), table_name='agent_trace')
    op.drop_table('agent_trace')
    # ### end Alembic commands ###
